name: Android CI

on:
  push:
    branches: [ "master", "v*" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./studio-android/LightNovelLibrary

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 修改1：彻底删掉模拟器和测试，直接执行组装打包命令
    - name: Build APK
      run: ./gradlew assembleAlpha

    # 修改2：增加一个上传步骤，把打好的 APK 提取到页面底部的 Artifacts 中供你下载
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Wenku8-App-Fixed
        path: studio-android/LightNovelLibrary/app/build/outputs/apk/alpha/debug/*.apk
